# Generated by Django 4.1.2 on 2022-10-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('review', models.TextField()),
                ('star', models.IntegerField()),
                ('emoji', models.CharField(max_length=20)),
                ('img', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
