# Generated by Django 4.1.2 on 2022-10-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='instagram/post/%Y%m%d')),
                ('is_public', models.BooleanField(default=False, verbose_name='공개여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mvcode', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='mvcode',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
