# Generated by Django 4.1.2 on 2022-10-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_post_review_mvcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='mvRank',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
