# Generated by Django 4.1.2 on 2022-10-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_review_mvrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='mvNm',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
