# Generated by Django 4.1.2 on 2022-10-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_review_mvnm'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='viewIdx',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
